### ISSUE TITLE
Update bootstrap-switch-nuget version

### ISSUE THREAD

**Issue by WilliamFei** [blachniet/bootstrap-switch-nuget#10]
Could you help to update bootstrap-switch to  v3.3.4

**Comment by blachniet** [comment]
I pushed a new version to NuGet, [here](https://www.nuget.org/packages/Bootstrap.Switch/3.3.4) and [here](https://www.nuget.org/packages/Bootstrap.Switch.Less).

I haven't used this project in a very long time, and I don't have the setup to really test the new packages. Let me know if something doesn't look right.
