### ISSUE TITLE
Change LESS version of package to depend on Twitter.Bootstrap.Less vs bootstrap

### ISSUE THREAD

**Issue by tomgruszowski** [blachniet/bootstrap-switch-nuget#8]
A LESS Bootstrap plugin should probably depend on a LESS based bootstrap (nuget dependency).

Recommended package : https://www.nuget.org/packages/Twitter.Bootstrap.Less

It doesn't seem like bootstrap team is going to publish an official nuget less package any-time soon and this is the defacto standard with over 300k downloads and timely updates.

As an optional suggestion maybe remove the dependency all together, not sure why anyone would ever run this plugin without already having bootstrap installed. One doesn't just work with LESS without having a more comprehensive understanding of these dependencies.

**Comment by blachniet** [comment]
The more I thought about it, the more I liked the idea of removing the dependency altogether. The [official package over on npm](https://www.npmjs.com/package/bootstrap-switch) does not have a dependency on bootstrap, so the NuGet package probably should not have it either. However, the official package does have a dependency on jquery. Maybe we should include that dependency in the NuGet package as well. Thoughts?

**Comment by tomgruszowski** [comment]
No dependency probably best. Honestly I've been playing with the new gulp bower stuff lately and going forward that should be much simpler than nuget as official packages have it all. But thy will take a while to switch everyone over.

I think the main point is no one will just use a 3rd party bootstrap library without already having bootstrap so that dependency is almost pointless. it's a library 1% size of bootstrap that requires the other 99%, don't think anyone will accidents overlook this :)

**Comment by blachniet** [comment]
I removed the dependency in [v3.3.2.1](https://github.com/blachniet/bootstrap-switch-nuget/releases/tag/v3.3.2.1). Thank you for your patience and feedback!
